---
- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Restart loki service
  become: true
  systemd:
    name: loki
    state: restarted
    enabled: yes

- name: Clean loki temp files
  become: true
  file:
    path: "{{ loki_tmp_dir }}"
    state: absent
